
export const ADD_APPOINTMENT_REQUEST = 'ADD_APPOINTMENT_REQUEST'
export const ADD_APPOINTMENT_SUCCESS = 'ADD_APPOINTMENT_SUCCESS'
export const ADD_APPOINTMENT_FAIL = 'ADD_APPOINTMENT_FAIL'
export const ADD_APPOINTMENT_RESET = 'ADD_APPOINTMENT_RESET'

export const UPDATE_APPOINTMENT_REQUEST = 'UPDATE_APPOINTMENT_REQUEST'
export const UPDATE_APPOINTMENT_SUCCESS = 'UPDATE_APPOINTMENT_SUCCESS'
export const UPDATE_APPOINTMENT_FAIL = 'UPDATE_APPOINTMENT_FAIL'
export const UPDATE_APPOINTMENT_RESET = 'UPDATE_APPOINTMENT_RESET'

export const GET_ALL_APPOINTMENT_REQUEST = 'GET_ALL_APPOINTMENT_REQUEST'
export const GET_ALL_APPOINTMENT_SUCCESS = 'GET_ALL_APPOINTMENT_SUCCESS'
export const GET_ALL_APPOINTMENT_FAIL = 'GET_ALL_APPOINTMENT_FAIL'

export const GET_ALL_APPOINTMENT_BY_DATE_REQUEST = 'GET_ALL_APPOINTMENT_BY_DATE_REQUEST'
export const GET_ALL_APPOINTMENT_BY_DATE_SUCCESS = 'GET_ALL_APPOINTMENT_BY_DATE_SUCCESS'   
export const GET_ALL_APPOINTMENT_BY_DATE_FAIL = 'GET_ALL_APPOINTMENT_BY_DATE_FAIL'

export const DELETE_APPOINTMENT_REQUEST = 'DELETE_APPOINTMENT_REQUEST'
export const DELETE_APPOINTMENT_SUCCESS = 'DELETE_APPOINTMENT_SUCCESS'
export const DELETE_APPOINTMENT_FAIL = 'DELETE_APPOINTMENT_FAIL'
export const DELETE_APPOINTMENT_RESET = 'DELETE_APPOINTMENT_RESET'

export const VERIFY_APPOINTMENT_REQUEST = 'VERIFY_APPOINTMENT_REQUEST'
export const VERIFY_APPOINTMENT_SUCCESS = 'VERIFY_APPOINTMENT_SUCCESS'
export const VERIFY_APPOINTMENT_FAIL = 'VERIFY_APPOINTMENT_FAIL'
export const CANCEL_APPOINTMENT_REQUEST = 'CANCEL_APPOINTMENT_REQUEST'
export const CANCEL_APPOINTMENT_SUCCESS = 'CANCEL_APPOINTMENT_SUCCESS'
export const CANCEL_APPOINTMENT_FAIL = 'CANCEL_APPOINTMENT_FAIL'

export const CHANGE_APPOINTMENT_REQUEST = 'CHANGE_APPOINTMENT_REQUEST'
export const CHANGE_APPOINTMENT_SUCCESS = 'CHANGE_APPOINTMENT_SUCCESS'
export const CHANGE_APPOINTMENT_FAIL = 'CHANGE_APPOINTMENT_FAIL'

