export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST'
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS'
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL'
export const SEND_MESSAGE_RESET = 'SEND_MESSAGE_RESET'

export const GET_ALL_CONTACT_US_MESSAGE_REQUEST = 'GET_ALL_CONTACT_US_MESSAGE_REQUEST'
export const GET_ALL_CONTACT_US_MESSAGE_SUCCESS = 'GET_ALL_CONTACT_US_MESSAGE_SUCCESS'
export const GET_ALL_CONTACT_US_MESSAGE_FAIL = 'GET_ALL_CONTACT_US_MESSAGE_FAIL'

export const DELETE_CONTACT_US_MESSAGE_REQUEST = 'DELETE_CONTACT_US_MESSAGE_REQUEST'
export const DELETE_CONTACT_US_MESSAGE_SUCCESS = 'DELETE_CONTACT_US_MESSAGE_SUCCESS'
export const DELETE_CONTACT_US_MESSAGE_FAIL = 'DELETE_CONTACT_US_MESSAGE_FAIL'
export const DELETE_CONTACT_US_MESSAGE_RESET = 'DELETE_CONTACT_US_MESSAGE_RESET'