
export const ADD_DOCTOR_REQUEST = 'ADD_DOCTOR_REQUEST'
export const ADD_DOCTOR_SUCCESS = 'ADD_DOCTOR_SUCCESS'
export const ADD_DOCTOR_FAIL = 'ADD_DOCTOR_FAIL'
export const ADD_DOCTOR_RESET = 'ADD_DOCTOR_RESET'

export const UPDATE_DOCTOR_REQUEST = 'UPDATE_DOCTOR_REQUEST'
export const UPDATE_DOCTOR_SUCCESS = 'UPDATE_DOCTOR_SUCCESS'
export const UPDATE_DOCTOR_FAIL = 'UPDATE_DOCTOR_FAIL'
export const UPDATE_DOCTOR_RESET = 'UPDATE_DOCTOR_RESET'

export const GET_ALL_DOCTOR_REQUEST = 'GET_ALL_DOCTOR_REQUEST'
export const GET_ALL_DOCTOR_SUCCESS = 'GET_ALL_DOCTOR_SUCCESS'
export const GET_ALL_DOCTOR_FAIL = 'GET_ALL_DOCTOR_FAIL'

export const DELETE_DOCTOR_REQUEST = 'DELETE_DOCTOR_REQUEST'
export const DELETE_DOCTOR_SUCCESS = 'DELETE_DOCTOR_SUCCESS'
export const DELETE_DOCTOR_FAIL = 'DELETE_DOCTOR_FAIL'
export const DELETE_DOCTOR_RESET = 'DELETE_DOCTOR_RESET'